---
title: "Bank-Marketing"
knit: (function(input, ...) {rmarkdown::render(input, output_file="../docs/Bank-Marketing.html")})

output:
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 3
    number_sections: true
    toc_float:
      collapsed: true
    css: "../docs/styles.css"
---

_Authors_: [Mauro Venticinque](https://it.linkedin.com/in/mauro-venticinque-01a297212) | [Angelo Schillaci](https://www.linkedin.com/in/angelo-schillaci-095064213) | [Daniele Tambone](https://www.linkedin.com/in/daniele-tambone-b5733616a)

_GitHub project_: [Bank-Marketing](https://github.com/DanieleT25/Bank-Marketing)

_Date_: `r Sys.Date()`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(DT)
library(visdat)
library(readr)
library(skimr)
library(ggplot2)
library(GGally)
library(corrplot)
library(plotly)
library(Hmisc)
library(patchwork)
library(dplyr)

library(MASS)
library(car)
library(caret)
library(ISLR)
library(ISLR2)
library(tidyverse)
library(glmnet)
library(pROC)

library(tree)
library(randomForest)
library(BART)
```

```{r, echo=FALSE, message=FALSE}
train <- read.csv("../data/raw/bank_marketing_train.csv")
train <- train %>% dplyr::select(-X)
attach(train)
```


```{r child="introduction.Rmd"} 
```

```{r child="EDA.Rmd"}
```

```{r child="modelSelection.Rmd"}
```
